Algoritmo "Horas Iguais"
//
//
// Descrição   : Compara dois horarios e mostra o mais tarde
// Autor(a)    : Claudio D'Silva
// Data atual  : 19/03/2026
Var
   h1:inteiro
   h2:inteiro


Inicio
      escreva("Informe a primeira número:")
      leia(h1)
      escreva("Informe a segunda número:")
      leia(h2)

      se (h1>h2) entao
         escreva(h1, " é mais tarde que ", h2)
      senao
           escreva(h2, " é mais tarde que ", h1)
      fimse


Fimalgoritmo